version: "3.7"
name: lms
services:
  mariadb:
    image: mariadb:10.6
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mariadb-data:/var/lib/mysql/

  redis:
    image: redis:alpine

  frappe:
    image: frappe/bench:latest
    command: bash /workspace/init.sh
    environment:
      - SHELL=/bin/bash
    working_dir: /home/frappe
    volumes:
      - .:/workspace
      # - frappe-data:/home/frappe/
      - frappe-data-2:/home/frappe/
      # - frappe-app-data:/home/frappe/frappe-bench/apps/
      # - frappe-app-frappe-data:/home/frappe/frappe-bench/apps/frappe/
      # - frappe-app-lms-data:/home/frappe/frappe-bench/apps/lms/
      # - frappe-log-data:/home/frappe/frappe-bench/sites/lms.localhost/logs/
      # - frappe-log-data:/home/frappe/frappe-bench/sites/lms.localhost/logs/
    ports:
      - 8000:8000
      - 9000:9000

volumes:
  mariadb-data:
  frappe-data:
  frappe-data-2:
  # frappe-app-data:
  # frappe-app-frappe-data:
  # frappe-app-lms-data:
  # frappe-log-data:
    
